image: alpine:latest

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          - apk add --no-cache git openssh
          - git config --global user.name "Luis Imperial (Bitbucket Sync Bot)"
          - git config --global user.email "imperialluisanton@outlook.ph"
          - git clone --mirror https://luisapi-admin@bitbucket.org/luisapi/basa-chatbot.git
          - cd basa-chatbot.git
          - git remote add github https://LuisAPI:$GITHUB_TOKEN@github.com/LuisAPI/BASA-Chatbot.git
          - git push --mirror github
